### PR TITLE
Prevent app breaks on loading accent color failed.

### LINKED ISSUE #18: Fail on iOS with fallbackColor set.
Env:
- Host
  - MacOS 12.6.2
  - Flutter 3.10.3 (Dart 3.0.3) stable channel
- Target
  - iPhone 14 (simulator)
  - iOS 16.2

Code: 
```dart
void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  SystemTheme.fallbackColor = const Color(0xFF1f1e33);
  await SystemTheme.accentColor.load();

  runApp(MyApp());
}
```

Error stack:
```
[VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: MissingPluginException(No implementation found for method SystemTheme.accentColor on channel system_theme)
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:308:7)
<asynchronous suspension>
#1      SystemAccentColor.load (package:system_theme/system_theme.dart:88:20)
<asynchronous suspension>
[VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: MissingPluginException(No implementation found for method SystemTheme.accentColor on channel system_theme)
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:308:7)
<asynchronous suspension>
#1      SystemAccentColor.load (package:system_theme/system_theme.dart:88:20)
<asynchronous suspension>
#2      main (package:playground/main.dart:8:3)
<asynchronous suspension>
```

### PR DESCRIPTION
**Pull request by kj415j45**
Could be a viable patch that resolve #18 before #12 got implement.

### CODE REVIEW

File: lib/system_theme.dart [hunk 1]
```diff
@@ -84,17 +84,21 @@ class SystemAccentColor {
...
+      accent = _retrieve(colors['accent'])!;
+      light = _retrieve(colors['light']) ?? accent;
+      lighter = _retrieve(colors['lighter']) ?? accent;
+      lightest = _retrieve(colors['lightest']) ?? accent;
+      dark = _retrieve(colors['dark']) ?? accent;
+      darker = _retrieve(colors['darker']) ?? accent;
+      darkest = _retrieve(colors['darkest']) ?? accent;
+    } catch (e) {
+      return;
+    }
```
Comment (bdlukaa) [inline lib/system_theme.dart]: I think only platform exceptions should be handled. What do you think?

```suggestion
    } on PlatformException catch (e) {
      return;
    } catch (e) {
      rethrow;
    }
```

Comment (kj415j45) [reply lib/system_theme.dart]:
```suggestion
    } on MissingPluginException catch (e) {
      return;
    } catch (e) {
      rethrow;
    }
```
It's weird that I found that this lib not implements iOS platform plugin. That's why #18 happened: Flutter tries to load platform channel but there is none. So `MissingPluginException` should be handled instead.

I was confused with iOS support in `README.md`, while it is actually unsupported in `pubspec.yaml`

Comment (bdlukaa) [reply lib/system_theme.dart]: As it seems like, iOS doesn't have a native method that refers to the system colors - and I don't even think there is such thing as system theme on iOS. iOS support on README refers to the support to the `isDarkMode` implementation.

I still think it is valid to check if the system is iOS and do not call the platform method
